### ISSUE TITLE
Timestamp logging changes

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/json-rails-logger#20]
Per the request from @andrew-pickin-epi, can you please:

- add milliseconds to the formatted timestamp
- change the key from `timestamp` to `ts`

**Comment by andrew-pickin-epi** [comment]
We probably need to standardise on a timestamp format as it looks like the buffering of docker/syslog/fluentd is bunching events and losing the required precision. 
It does appear, however, that there is a solution to re-index event with a fluentd filter using the client level timestamp.
In short this field isn't just about usability now, it's vital to sequencing.
I'm minded to say %Y-%m-%dT%H:%M:%S.%nNZ (or %FT%T.%nNZ) where n is 3 (or 6/9), but this will need to be co-ordinated with the parser.

**Comment by bogdanadrianmarc** [comment]
@andrew-pickin-epi Does the `Z` at the end stand for timezone? https://apidock.com/ruby/DateTime/strftime

**Comment by andrew-pickin-epi** [comment]
No the Z is a literal (like the T between the date & time), and (I think) is supposed to indicate Zulu time aka UTC/GMT

**Comment by bogdanadrianmarc** [comment]
Done 👍
