### ISSUE TITLE
Triggering the gem publication workflow

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/json-rails-logger#36]
I don't seem to be able to trigger the workflow that publishes the gem to the GitHub registry. I've just updated to version 0.3.2, and tagged and pushed `main`. But the [latest version](https://github.com/epimorphics/json-rails-logger/releases) is still showing as 0.2.2

@andrew-pickin-epi Any suggestions?

**Comment by ijdickinson** [comment]
I think the problem may be that the publish action in the GH workflow triggers on push. When I want to make a change, I push it to a branch, PR it, and then it gets reviewed. Only after review does it get merged. Then, after it's merged, I can tag that release. But at that point, there's nothing new to push (`git push --follow-tags` pushes the new tag to `origin`, but that doesn't seem to trigger the workflow).

**Comment by andrew-pickin-epi** [comment]
It's only been tagged. This tag now needs to be released.

https://github.com/epimorphics/json-rails-logger/releases/tag/0.3.2

I guess this could all be built into the workflow. But as I said before I was uncomfortable defining a process for these artefacts as I don't develop them.
