### ISSUE TITLE
JSON Rails Logger: Ruby Upgrade 2.7.8

### ISSUE THREAD

**Issue by DanielCouzens** [epimorphics/json-rails-logger#54]
Upgrades ruby to 2.7.8

**Comment by DanielCouzens** [comment]
This is in review PR https://github.com/epimorphics/json-rails-logger/pull/55

**Comment by DanielCouzens** [comment]
Test this works with the repos that use it

- [ ] Lr-landing-page
- [ ] PPD
- [ ] Standard reports
- [ ] UKHPI

**Comment by DanielCouzens** [comment]
this has been merged into main https://github.com/epimorphics/json-rails-logger/pull/55

**Comment by bogdanadrianmarc** [comment]
Closing as ruby version is now `3.3.5` for the gem

**Comment by tomguilbert** [comment]
Although this is closed, it is still in the Main/Dev/Master column of the parent project. Is it done @bogdanadrianmarc?

**Comment by bogdanadrianmarc** [comment]
> Although this is closed, it is still in the Main/Dev/Master column of the parent project. Is it done [@bogdanadrianmarc](https://github.com/bogdanadrianmarc)?

It is done, in this case there's only the `main` branch as this is an internal gem that we use. So anything that's on `main` is actually "released"
